config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :publications, :only => [:index, :show]

  resources :people, :only => [:index, :show]

  devise_for :users
  
  root "publications#index"

end

app/models/person.rb
class Person < ActiveRecord::Base
  has_and_belongs_to_many :publications
  
  mount_uploader :photo, PhotoUploader
  
  validates :first_name, :last_name, :email, :presence => true
  
  
  def name
    [first_name, last_name].join(" ")
  end
end

app/models/publication.rb
class Publication < ActiveRecord::Base
  has_and_belongs_to_many :people
  
  mount_uploader :pub_image, PubImageUploader
  
  validates :name, :headline, :description_text, :pub_date, :presence => true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  
  def index
    @people = Person.all
  end
  
  def show
    @person = Person.find(params[:id])
  end

end

app/controllers/publications_controller.rb
class PublicationsController < ApplicationController
  def index
    @publications = Publication.all
  end
  
  def show
    @publication = Publication.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/helpers/publications_helper.rb
module PublicationsHelper
end

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
	<div class="navbar-inner">
		<div class="container">
			<div class="navbar-header">
				<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse">
					<span class="sr-only">Toggle navigation</span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
				</button>
				<a class="navbar-brand hidden-sm" href="/">Pubster</a>
			</div>
		
			<div class="navbar-collapse collapse" id="navbar-collapse">
				<ul class="nav navbar-nav navbar-right">
					<li>
						<%= link_to "People", people_path, :class => "navbar-link" %>
					</li>
					<li><%= link_to "Publications", publications_path, :class => "navbar-link" %></li>
				</ul>
			</div>
		</div>
	</div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<meta name="viewport" content="width=device-width initial-scale=1">
  	<title>Publications</title>
	<%= stylesheet_link_tag "https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css" %>
	<%= stylesheet_link_tag "https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css" %>
  	<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  	<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>
  	<%= csrf_meta_tags %>
</head>
<body id="<%= controller.controller_name %>">
	<%= render :partial => "layouts/nav" %>
	
	<div class="container">
		<div class="row">
			<div class="col-xs-12">
				<%= yield %>
			</div>
		</div>
	</div>

</body>
</html>

app/views/people/index.html.erb
<div class="row">
	<div class="col-sm-12">
		<h2>People</h2>
		<hr />
		<% if @people.empty? %>
			<p>Currently there are no people</p>
		<% else %>
			<% @people.in_groups_of(4) do |group| %>
				<div class="row">
					<% group.compact.each do |person| %>
						<div class="col-sm-3 text-center image-box">
							<div>
								<%= link_to person_path(person), {} do %> 
									<% if person.photo.present? %>
										<img u="pub-image" src="<%= person.photo.thumb.url %>" alt=""/>
									<% else %>
										<i class="fa fa-user fa-big" u="pub-image"></i>
									<% end %>
								<% end %>
								<h4><%= link_to person.name, person_path(person) %></h4>
							</div>
						</div>
					<% end %>
				</div>
			<% end %>
		<% end %>
	</div>
</div>

app/views/people/show.html.erb
<div class="row">
	<div class="col-sm-12">
		<h2><%= @person.name %></h2>
		<hr />
		<div class="row">
			<% if @person.photo.present? %>
				<div class="col-sm-4">
					<div>
						<img src="<%= @person.photo.url %>" alt=""/>
					</div>
				</div>
			<% end %>
			<% column_size = @person.photo.present? ? "col-sm-8" : "col-sm-12" %>
			<div class="<%= column_size %>">
				<% if @person.job_title.present? %>
					<h3><%= @person.job_title %></h3>
				<% end %>
				<p><%= @person.bio %></p>
			</div>
		</div>
		<% if @person.publications.size > 0 %>
			<div class="row">
				<div class="col-sm-12">
					<h4>Publications by <%= @person.name %></h4>
					<hr />
					<% @person.publications.each do |publication| %>
						<div class="col-sm-6">
							<p><%= link_to publication.name, publication_path(publication) %></p>
						</div>
					<% end %>
				</div>
			</div>
		<% end %>
	</div>
</div>

app/views/publications/index.html.erb
<div class="row">
	<div class="col-sm-12">
		<h2>Publications</h2>
		<hr />
		<% if @publications.empty? %>
			<p>Currently there are no publications</p>
		<% else %>
			<% @publications.in_groups_of(4) do |group| %>
				<div class="row">
					<% group.compact.each do |publication| %>
						<div class="col-sm-3 text-center image-box">
							<div>
								<%= link_to publication_path(publication), {} do %> 
									<% if publication.pub_image.present? %>
										<img u="pub-image" src="<%= publication.pub_image.thumb.url %>" />
									<% else %>
										<i class="fa fa-book fa-big" u="pub-image"></i>
									<% end %>
								<% end %>
								<h4><%= link_to publication.name, publication_path(publication) %></h4>
							</div>
						</div>
					<% end %>
				</div>
			<% end %>
		<% end %>
	</div>
</div>

app/views/publications/show.html.erb
<div class="row">
	<div class="col-sm-12">
		<h2><%= @publication.name %></h2>
		<hr />
		<div class="row">
			<% if @publication.pub_image.present? %>
				<div class="col-sm-4">
					<div>
						<img src="<%= @publication.pub_image.url %>" alt=""/>
					</div>
				</div>
			<% end %>
			<% column_size = @publication.pub_image.present? ? "col-sm-8" : "col-sm-12" %>
			<div class="<%= column_size %>">
				<h3><%= @publication.headline %></h3>
				<% if @publication.pub_date.present? %>
					<p><%= @publication.pub_date.to_formatted_s(:long) %></p>
				<% end %>
				<p><%= @publication.description_text %></p>
			</div>
		</div>
		<% if @publication.people.size > 0 %>
			<div class="row">
				<div class="col-sm-12">
					<h4>People in this Publication</h4>
					<hr />
					<% @publication.people.each do |person| %>
						<div class="col-sm-6">
							<p><%= link_to person.name, person_path(person) %></p>
						</div>
					<% end %>
				</div>
			</div>
		<% end %>
	</div>
</div>